development:
  adapter: postgresql
  encoding: unicode
  database: chat_app_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: chat_app_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: chat_app_production
  pool: 5
  username: chat_app
  password: